apiVersion: apps/v1
kind: Deployment
metadata:
  name: creativegang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: creativegang
  template:
    metadata:
      labels:
        app: creativegang
    spec:
      containers:
        - name: creativegangeks
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: creativegang
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: creativegang
