apiVersion: apps/v1
kind: Deployment
metadata:
  name: creativegang-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creativegang
  template:
    metadata:
      labels:
        app: creativegang
    spec:
      containers:
        - name: creativegangeks
          image: 713495193197.dkr.ecr.us-west-2.amazonaws.com/creativegangbackend:latest
          ports:
            - containerPort: 3000
         
---
apiVersion: v1
kind: Service
metadata:
  name: creativegang-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: creativegang
